# This file was generated by GoReleaser. DO NOT EDIT.
class GoSlalom < Formula
  desc "A golang sample webapp."
  homepage "https://github.com/tredfield/go-slalom"
  url "https://github.com/tredfield/go-slalom/releases/download/v0.0.1/go-slalom_0.0.1_Darwin_x86_64.tar.gz"
  version "0.0.1"
  sha256 "9cba2611fc43c9339e6a0d35d7bd4bc74d20db562cca88fef975fafe81a97828"

  def install
    bin.install "go-slalom"
  end
end
